### ISSUE TITLE
Hi, author. Can you tell me about yours drive fix work.

### ISSUE THREAD

**Issue by nekoctl** [herecura/broadcom-wl-bede#1]
Today, I try to use official drive, but when I make it, it give me a error.

```
/usr/src/linux-3.16.7-21/scripts/Makefile.build:273: recipe for target '/path/to/src/wl/sys/wl_cfg80211_hybrid.o' failed
```

So, if your patch can work, tell me how to use, I need it.

**Comment by BlackIkeEagle** [comment]
@GroverChouT this broadcom driver requires the linux-bede package. It builds just fine for that kernel.

If you want to build for other kernels I suggest you checkout https://aur4.archlinux.org/packages/broadcom-wl-dkms
